//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETLProcessLoggerDetail
    {
        public long PK_ETLProcessLoggerDetail_Id { get; set; }
        public int FK_ETLProcessLogger_Id { get; set; }
        public Nullable<byte> ProcessStatus { get; set; }
        public string Description { get; set; }
    }
}
