//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETLProcessLogger
    {
        public int PK_ETLProcessLogger_Id { get; set; }
        public string ETLName { get; set; }
        public string FullETLName { get; set; }
        public Nullable<System.DateTime> StartProcess { get; set; }
        public Nullable<System.DateTime> EndProcess { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
