//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenerateXbrlInstanceMonitor
    {
        public int PK_GenerateXbrlInstanceMonitor_Id { get; set; }
        public string TaxoDate { get; set; }
        public string UserProcess { get; set; }
        public string BankCode { get; set; }
        public Nullable<byte> Status { get; set; }
        public string StatusDesc { get; set; }
        public Nullable<System.DateTime> ReportingDate { get; set; }
    }
}
