//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LBUSYRForm02XBRL_TI
    {
        public int Period { get; set; }
        public string BIBankId { get; set; }
        public string SandiFormulir { get; set; }
        public string BulanData { get; set; }
        public string TahunData { get; set; }
        public Nullable<int> No { get; set; }
        public string Description { get; set; }
        public Nullable<int> Sandi { get; set; }
        public Nullable<decimal> Rupiah { get; set; }
        public Nullable<decimal> Valas { get; set; }
        public Nullable<decimal> IDRNonPenduduk { get; set; }
        public Nullable<decimal> ValasNonPenduduk { get; set; }
        public Nullable<decimal> Jumlah { get; set; }
    }
}
