//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LBUSYRForm2AXBRL_TI
    {
        public int Period { get; set; }
        public string BIBankId { get; set; }
        public string SandiFormulir { get; set; }
        public string BulanData { get; set; }
        public string TahunData { get; set; }
        public Nullable<int> No { get; set; }
        public string Description { get; set; }
        public string Sandi { get; set; }
        public Nullable<decimal> BankLain { get; set; }
        public Nullable<decimal> PemerintahEntitasSektorPublik { get; set; }
        public Nullable<decimal> LembagaKeuanganNonBank { get; set; }
        public Nullable<decimal> Lainnya { get; set; }
        public Nullable<decimal> Jumlah { get; set; }
        public Nullable<decimal> NonUMK { get; set; }
        public Nullable<decimal> UMK { get; set; }
    }
}
