//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsApprovalDetail
    {
        public int PK_MsApprovalDetail_Id { get; set; }
        public int FK_MsApprovalHeader_Id { get; set; }
        public string FieldName { get; set; }
        public string FieldValue_New { get; set; }
        public string FieldValue_Old { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
