//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsUser
    {
        public int PK_MsUser_Id { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> FK_MsGroupMenu_Id { get; set; }
        public Nullable<int> FK_MsGroupApproval_Id { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
        public Nullable<System.DateTime> LastChangePassword { get; set; }
        public string UsedInIPAddress { get; set; }
        public Nullable<bool> IsInUsed { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<byte> CheckerMakerLevel { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string BranchCode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public string LastUpdateBy { get; set; }
    }
}
