//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageIndex
    {
        public int IndexId { get; set; }
        public string tfInstance { get; set; }
        public string labelId { get; set; }
        public string tvId { get; set; }
        public string tfCode { get; set; }
    }
}
