//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicesTaskCheckerStatus
    {
        public int PK_ServicesTaskCheckerStatus_Id { get; set; }
        public string ProcessName { get; set; }
        public Nullable<byte> ProcessType { get; set; }
        public Nullable<byte> Status { get; set; }
    }
}
