//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnMappedForm
    {
        public int PK_UnMappedForm_Id { get; set; }
        public string FormName { get; set; }
        public string TaxoVersion { get; set; }
    }
}
