//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadTaxoProgress
    {
        public int PK_UploadTaxoProgress_Id { get; set; }
        public string ProgressName { get; set; }
        public Nullable<byte> Status { get; set; }
    }
}
