//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValidateAllTechnicalValidation
    {
        public int PK_ValidateAllTechnicalValidation_Id { get; set; }
        public string FormName { get; set; }
        public Nullable<int> ErrorRowNumber { get; set; }
        public Nullable<byte> ProgressStatus { get; set; }
        public string ProgressDescription { get; set; }
    }
}
