//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AuditTrailHeader
    {
        public long PK_AuditTrailHeader_Id { get; set; }
        public Nullable<System.DateTime> ExecutedDate { get; set; }
        public string ExecuteBy { get; set; }
        public string UserName { get; set; }
        public Nullable<byte> Mode { get; set; }
        public string Description { get; set; }
        public string ModeDesc { get; set; }
        public Nullable<long> RowNumber { get; set; }
    }
}
