//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Form27
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public int si230 { get; set; }
        public string si178 { get; set; }
        public int di176 { get; set; }
        public int si202 { get; set; }
        public int mi231 { get; set; }
        public int mi232 { get; set; }
        public int mi233 { get; set; }
    }
}
