//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Form03
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string si2 { get; set; }
        public Nullable<decimal> mi3 { get; set; }
        public Nullable<decimal> mi4 { get; set; }
        public Nullable<decimal> mi5 { get; set; }
        public Nullable<decimal> mi6 { get; set; }
        public Nullable<decimal> mi7 { get; set; }
    }
}
