//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Form32
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string si14 { get; set; }
        public string si15 { get; set; }
        public string si16 { get; set; }
        public string si17 { get; set; }
        public string si69 { get; set; }
        public string si259 { get; set; }
        public string si2 { get; set; }
        public string di9 { get; set; }
        public string di10 { get; set; }
        public string si432 { get; set; }
        public string si250 { get; set; }
        public Nullable<decimal> pi251 { get; set; }
        public Nullable<decimal> pi50 { get; set; }
        public Nullable<decimal> pi12 { get; set; }
        public Nullable<decimal> mi260 { get; set; }
        public Nullable<decimal> mi261 { get; set; }
        public Nullable<decimal> mi262 { get; set; }
        public Nullable<decimal> mi263 { get; set; }
        public Nullable<decimal> mi264 { get; set; }
    }
}
