//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Form50
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string si398 { get; set; }
        public string si421 { get; set; }
        public string si83 { get; set; }
        public string si434 { get; set; }
        public string si392 { get; set; }
        public string si394 { get; set; }
        public Nullable<decimal> mi406 { get; set; }
        public Nullable<decimal> mi407 { get; set; }
        public Nullable<decimal> mi408 { get; set; }
    }
}
