//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Form14
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string si27 { get; set; }
        public string si28 { get; set; }
        public string si80 { get; set; }
        public string si29 { get; set; }
        public string di30 { get; set; }
        public Nullable<decimal> mi31 { get; set; }
        public Nullable<decimal> mi60 { get; set; }
        public Nullable<decimal> pi59 { get; set; }
        public string si68 { get; set; }
        public string si421 { get; set; }
        public string si15 { get; set; }
        public string si16 { get; set; }
        public string si83 { get; set; }
        public string si188 { get; set; }
        public string si2 { get; set; }
        public string di9 { get; set; }
        public string di10 { get; set; }
        public string si11 { get; set; }
        public string si84 { get; set; }
        public string si85 { get; set; }
        public string si86 { get; set; }
        public string si434 { get; set; }
        public string si87 { get; set; }
        public string si394 { get; set; }
        public string si140 { get; set; }
        public string si71 { get; set; }
        public string si19 { get; set; }
        public string di72 { get; set; }
        public string si141 { get; set; }
        public int si142 { get; set; }
        public string di176 { get; set; }
        public string si143 { get; set; }
        public Nullable<decimal> mi144 { get; set; }
        public string mi145 { get; set; }
        public string si146 { get; set; }
        public string si147 { get; set; }
        public Nullable<decimal> mi148 { get; set; }
        public int mi149 { get; set; }
        public Nullable<decimal> pi12 { get; set; }
        public Nullable<decimal> mi150 { get; set; }
        public Nullable<decimal> mi151 { get; set; }
        public Nullable<decimal> mi152 { get; set; }
        public Nullable<decimal> mi153 { get; set; }
        public Nullable<decimal> mi154 { get; set; }
        public Nullable<decimal> mi155 { get; set; }
        public string si58 { get; set; }
        public Nullable<decimal> mi156 { get; set; }
        public Nullable<decimal> mi157 { get; set; }
    }
}
