//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_FormAnak10
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string si27 { get; set; }
        public string si28 { get; set; }
        public string si80 { get; set; }
        public string si29 { get; set; }
        public string di30 { get; set; }
        public Nullable<decimal> mi31 { get; set; }
        public Nullable<decimal> mi60 { get; set; }
        public Nullable<decimal> pi59 { get; set; }
        public string si68 { get; set; }
        public string si421 { get; set; }
        public string si15 { get; set; }
        public string si16 { get; set; }
        public string si83 { get; set; }
        public string si188 { get; set; }
        public string si2 { get; set; }
        public string di10 { get; set; }
        public string di9 { get; set; }
        public string si11 { get; set; }
        public string si392 { get; set; }
        public string si121 { get; set; }
        public string si122 { get; set; }
        public string si434 { get; set; }
        public string si87 { get; set; }
        public string si394 { get; set; }
        public string si140 { get; set; }
        public string si71 { get; set; }
        public string si19 { get; set; }
        public string di72 { get; set; }
        public string si124 { get; set; }
        public string si317 { get; set; }
        public string si250 { get; set; }
        public Nullable<decimal> pi251 { get; set; }
        public Nullable<decimal> mi125 { get; set; }
        public Nullable<decimal> pi50 { get; set; }
        public Nullable<decimal> pi12 { get; set; }
        public Nullable<decimal> pi126 { get; set; }
        public Nullable<decimal> mi127 { get; set; }
        public Nullable<decimal> mi128 { get; set; }
        public Nullable<decimal> mi129 { get; set; }
        public Nullable<decimal> mi130 { get; set; }
        public Nullable<decimal> mi131 { get; set; }
        public Nullable<decimal> mi132 { get; set; }
        public Nullable<decimal> mi133 { get; set; }
        public Nullable<decimal> mi134 { get; set; }
        public Nullable<decimal> mi135 { get; set; }
        public string si58 { get; set; }
        public Nullable<decimal> mi136 { get; set; }
        public Nullable<decimal> mi137 { get; set; }
    }
}
