//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Form37
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string si68 { get; set; }
        public string si422 { get; set; }
        public string si15 { get; set; }
        public string si16 { get; set; }
        public string si2 { get; set; }
        public string di9 { get; set; }
        public string di10 { get; set; }
        public string si294 { get; set; }
        public Nullable<decimal> mi295 { get; set; }
        public Nullable<decimal> mi296 { get; set; }
        public Nullable<decimal> mi297 { get; set; }
        public Nullable<decimal> mi298 { get; set; }
        public Nullable<decimal> mi299 { get; set; }
    }
}
