//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Form34
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string si68 { get; set; }
        public string si423 { get; set; }
        public string si15 { get; set; }
        public string si16 { get; set; }
        public string si69 { get; set; }
        public string si268 { get; set; }
        public string si284 { get; set; }
        public string si43 { get; set; }
        public string si2 { get; set; }
        public string di9 { get; set; }
        public string di10 { get; set; }
        public string si44 { get; set; }
        public string si433 { get; set; }
        public string si250 { get; set; }
        public Nullable<decimal> pi251 { get; set; }
        public Nullable<decimal> mi269 { get; set; }
        public string si49 { get; set; }
        public Nullable<decimal> pi50 { get; set; }
        public Nullable<decimal> pi12 { get; set; }
        public Nullable<decimal> mi270 { get; set; }
        public Nullable<decimal> mi271 { get; set; }
        public Nullable<decimal> mi272 { get; set; }
        public Nullable<decimal> mi273 { get; set; }
        public Nullable<decimal> mi274 { get; set; }
        public Nullable<decimal> mi275 { get; set; }
    }
}
