//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Form18
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string si68 { get; set; }
        public string si425 { get; set; }
        public string si15 { get; set; }
        public string si16 { get; set; }
        public string si83 { get; set; }
        public string si188 { get; set; }
        public string si2 { get; set; }
        public string di9 { get; set; }
        public string di10 { get; set; }
        public string si11 { get; set; }
        public string si84 { get; set; }
        public string si428 { get; set; }
        public Nullable<decimal> mi182 { get; set; }
        public Nullable<decimal> mi183 { get; set; }
        public Nullable<decimal> mi184 { get; set; }
        public Nullable<decimal> ii185 { get; set; }
        public Nullable<decimal> mi186 { get; set; }
    }
}
