//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Form41
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string si68 { get; set; }
        public string si423 { get; set; }
        public string si15 { get; set; }
        public string si16 { get; set; }
        public string si69 { get; set; }
        public string si314 { get; set; }
        public string si315 { get; set; }
        public string si2 { get; set; }
        public string di9 { get; set; }
        public string di10 { get; set; }
        public string si316 { get; set; }
        public string si317 { get; set; }
        public string si250 { get; set; }
        public Nullable<decimal> pi251 { get; set; }
        public Nullable<decimal> mi318 { get; set; }
        public Nullable<decimal> pi50 { get; set; }
        public Nullable<decimal> pi12 { get; set; }
        public Nullable<decimal> mi319 { get; set; }
        public Nullable<decimal> mi320 { get; set; }
        public Nullable<decimal> mi321 { get; set; }
        public Nullable<decimal> mi322 { get; set; }
        public Nullable<decimal> mi323 { get; set; }
    }
}
