//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Form35
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string si68 { get; set; }
        public string si421 { get; set; }
        public string si15 { get; set; }
        public string si16 { get; set; }
        public string si69 { get; set; }
        public string si2355 { get; set; }
        public string si2 { get; set; }
        public string di9 { get; set; }
        public string di10 { get; set; }
        public Nullable<decimal> mi277 { get; set; }
        public Nullable<decimal> pi12 { get; set; }
        public Nullable<decimal> mi278 { get; set; }
        public Nullable<decimal> mi279 { get; set; }
        public Nullable<decimal> mi280 { get; set; }
        public Nullable<decimal> mi281 { get; set; }
        public Nullable<decimal> mi282 { get; set; }
    }
}
