//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Form19
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string si68 { get; set; }
        public string si421 { get; set; }
        public string si15 { get; set; }
        public string si16 { get; set; }
        public string si187 { get; set; }
        public string si188 { get; set; }
        public string si178 { get; set; }
        public string di9 { get; set; }
        public string di10 { get; set; }
        public string si189 { get; set; }
        public string si190 { get; set; }
        public Nullable<decimal> mi191 { get; set; }
        public Nullable<decimal> pi192 { get; set; }
        public Nullable<decimal> mi193 { get; set; }
        public Nullable<decimal> mi194 { get; set; }
    }
}
