//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Form05
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string si14 { get; set; }
        public string si15 { get; set; }
        public string si16 { get; set; }
        public string si17 { get; set; }
        public string si69 { get; set; }
        public string si18 { get; set; }
        public string si2 { get; set; }
        public string di9 { get; set; }
        public string di10 { get; set; }
        public string si11 { get; set; }
        public string si71 { get; set; }
        public string si19 { get; set; }
        public string di72 { get; set; }
        public string si20 { get; set; }
        public string si250 { get; set; }
        public Nullable<decimal> pi251 { get; set; }
        public Nullable<decimal> pi50 { get; set; }
        public Nullable<decimal> pi12 { get; set; }
        public Nullable<decimal> mi21 { get; set; }
        public Nullable<decimal> mi22 { get; set; }
        public Nullable<decimal> mi23 { get; set; }
        public Nullable<decimal> mi24 { get; set; }
        public Nullable<decimal> mi25 { get; set; }
        public Nullable<decimal> mi26 { get; set; }
        public string si6017 { get; set; }
        public string si27 { get; set; }
        public string si28 { get; set; }
        public string si80 { get; set; }
        public string si29 { get; set; }
        public string di30 { get; set; }
        public Nullable<decimal> mi31 { get; set; }
        public Nullable<decimal> mi60 { get; set; }
        public Nullable<decimal> pi59 { get; set; }
        public Nullable<decimal> mi32 { get; set; }
        public Nullable<decimal> mi33 { get; set; }
    }
}
