//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_FormAnak09
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string si68 { get; set; }
        public string si421 { get; set; }
        public string si15 { get; set; }
        public string si16 { get; set; }
        public string si83 { get; set; }
        public string si188 { get; set; }
        public string si2 { get; set; }
        public string di9 { get; set; }
        public string di10 { get; set; }
        public string si11 { get; set; }
        public string si84 { get; set; }
        public string si111 { get; set; }
        public string si86 { get; set; }
        public string si434 { get; set; }
        public string si87 { get; set; }
        public string si394 { get; set; }
        public string si140 { get; set; }
        public string si71 { get; set; }
        public string si19 { get; set; }
        public string di72 { get; set; }
        public Nullable<decimal> mi112 { get; set; }
        public Nullable<decimal> pi50 { get; set; }
        public Nullable<decimal> pi12 { get; set; }
        public Nullable<decimal> mi113 { get; set; }
        public Nullable<decimal> mi114 { get; set; }
        public Nullable<decimal> mi115 { get; set; }
        public Nullable<decimal> mi116 { get; set; }
        public Nullable<decimal> mi117 { get; set; }
        public Nullable<decimal> mi118 { get; set; }
        public string si58 { get; set; }
        public string si27 { get; set; }
        public string si28 { get; set; }
        public string si80 { get; set; }
        public string si29 { get; set; }
        public string di30 { get; set; }
        public Nullable<decimal> mi31 { get; set; }
        public Nullable<decimal> mi60 { get; set; }
        public Nullable<decimal> pi59 { get; set; }
        public Nullable<decimal> mi119 { get; set; }
        public Nullable<decimal> mi120 { get; set; }
    }
}
