//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Form21
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string si175 { get; set; }
        public string si203 { get; set; }
        public string di204 { get; set; }
        public string si178 { get; set; }
        public string si197 { get; set; }
        public string si198 { get; set; }
        public Nullable<decimal> mi206 { get; set; }
        public Nullable<decimal> mi207 { get; set; }
        public string si6018 { get; set; }
        public Nullable<decimal> mi208 { get; set; }
        public string si202 { get; set; }
    }
}
