//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Form49
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string si398 { get; set; }
        public string si399 { get; set; }
        public Nullable<decimal> mi400 { get; set; }
        public Nullable<decimal> mi401 { get; set; }
        public Nullable<decimal> mi402 { get; set; }
        public Nullable<decimal> mi403 { get; set; }
        public Nullable<decimal> mi404 { get; set; }
        public Nullable<decimal> mi405 { get; set; }
    }
}
