//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Form43
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string mi6009 { get; set; }
        public string mi330 { get; set; }
        public string mi331 { get; set; }
        public string mi332 { get; set; }
        public string mi6010 { get; set; }
        public string mi343 { get; set; }
        public string mi344 { get; set; }
        public string mi345 { get; set; }
        public string mi327 { get; set; }
        public string mi328 { get; set; }
        public string mi329 { get; set; }
        public string mi340 { get; set; }
        public string mi341 { get; set; }
        public string mi342 { get; set; }
        public string mi6013 { get; set; }
        public string mi336 { get; set; }
        public string mi337 { get; set; }
        public string mi338 { get; set; }
        public string mi6014 { get; set; }
        public string mi349 { get; set; }
        public string mi350 { get; set; }
        public string mi351 { get; set; }
        public string mi333 { get; set; }
        public string mi334 { get; set; }
        public string mi335 { get; set; }
        public string mi346 { get; set; }
        public string mi347 { get; set; }
        public string mi348 { get; set; }
    }
}
