//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Form25
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string si221 { get; set; }
        public string si17 { get; set; }
        public string si222 { get; set; }
        public string si2 { get; set; }
        public Nullable<decimal> pi12 { get; set; }
        public Nullable<decimal> mi223 { get; set; }
        public Nullable<decimal> mi224 { get; set; }
        public Nullable<decimal> mi225 { get; set; }
        public Nullable<decimal> mi226 { get; set; }
        public Nullable<decimal> mi227 { get; set; }
    }
}
