//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Form07
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string si68 { get; set; }
        public string si423 { get; set; }
        public string si15 { get; set; }
        public string si16 { get; set; }
        public string si69 { get; set; }
        public string si42 { get; set; }
        public string si284 { get; set; }
        public string si43 { get; set; }
        public string si2 { get; set; }
        public string di9 { get; set; }
        public string di10 { get; set; }
        public string si11 { get; set; }
        public string si44 { get; set; }
        public string si37 { get; set; }
        public string si71 { get; set; }
        public string si19 { get; set; }
        public string di72 { get; set; }
        public string si46 { get; set; }
        public string si250 { get; set; }
        public decimal mi47 { get; set; }
        public Nullable<decimal> pi251 { get; set; }
        public Nullable<decimal> mi48 { get; set; }
        public string si49 { get; set; }
        public Nullable<decimal> pi50 { get; set; }
        public Nullable<decimal> pi12 { get; set; }
        public Nullable<decimal> mi51 { get; set; }
        public Nullable<decimal> mi52 { get; set; }
        public Nullable<decimal> mi53 { get; set; }
        public Nullable<decimal> mi54 { get; set; }
        public Nullable<decimal> mi55 { get; set; }
        public decimal mi56 { get; set; }
        public Nullable<decimal> mi57 { get; set; }
        public string si6017 { get; set; }
        public string si27 { get; set; }
        public string si28 { get; set; }
        public string si80 { get; set; }
        public string si29 { get; set; }
        public string di30 { get; set; }
        public Nullable<decimal> mi31 { get; set; }
        public Nullable<decimal> mi60 { get; set; }
        public Nullable<decimal> pi59 { get; set; }
        public Nullable<decimal> mi61 { get; set; }
        public Nullable<decimal> mi62 { get; set; }
    }
}
