//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Form39
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string si221 { get; set; }
        public string si17 { get; set; }
        public string si300 { get; set; }
        public string si2 { get; set; }
        public Nullable<decimal> pi12 { get; set; }
        public Nullable<decimal> mi303 { get; set; }
        public Nullable<decimal> mi304 { get; set; }
        public Nullable<decimal> mi305 { get; set; }
        public Nullable<decimal> mi306 { get; set; }
        public Nullable<decimal> mi307 { get; set; }
    }
}
