//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Form08
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string si188 { get; set; }
        public string si63 { get; set; }
        public string si429 { get; set; }
        public string di9 { get; set; }
        public string di10 { get; set; }
        public Nullable<decimal> pi12 { get; set; }
        public Nullable<decimal> mi64 { get; set; }
        public string si11 { get; set; }
        public Nullable<decimal> mi65 { get; set; }
        public Nullable<decimal> mi66 { get; set; }
        public Nullable<decimal> mi67 { get; set; }
    }
}
