//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Form15
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string si68 { get; set; }
        public string si421 { get; set; }
        public string si16 { get; set; }
        public string si69 { get; set; }
        public string si2 { get; set; }
        public string di158 { get; set; }
        public string si159 { get; set; }
        public string si160 { get; set; }
        public Nullable<decimal> pi161 { get; set; }
        public Nullable<decimal> mi162 { get; set; }
        public Nullable<decimal> mi163 { get; set; }
        public Nullable<decimal> mi164 { get; set; }
        public Nullable<decimal> mi165 { get; set; }
        public Nullable<decimal> mi166 { get; set; }
        public Nullable<decimal> mi167 { get; set; }
        public string si6018 { get; set; }
        public Nullable<decimal> mi60 { get; set; }
        public Nullable<decimal> mi168 { get; set; }
        public Nullable<decimal> mi169 { get; set; }
    }
}
