//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Form22
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string si175 { get; set; }
        public string si209 { get; set; }
        public string di176 { get; set; }
        public Nullable<decimal> mi210 { get; set; }
        public string si178 { get; set; }
        public Nullable<decimal> mi211 { get; set; }
        public Nullable<decimal> mi212 { get; set; }
        public Nullable<decimal> mi213 { get; set; }
        public Nullable<decimal> mi214 { get; set; }
        public string si426 { get; set; }
        public string si202 { get; set; }
    }
}
