//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Form44
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string si68 { get; set; }
        public string si421 { get; set; }
        public string si15 { get; set; }
        public string si16 { get; set; }
        public string si69 { get; set; }
        public string si369 { get; set; }
        public string si370 { get; set; }
        public string si35 { get; set; }
        public string si36 { get; set; }
        public string si371 { get; set; }
        public string si372 { get; set; }
        public string si1 { get; set; }
        public string si373 { get; set; }
        public string si374 { get; set; }
        public string di9 { get; set; }
        public string di10 { get; set; }
        public Nullable<decimal> mi375 { get; set; }
        public Nullable<decimal> mi376 { get; set; }
        public Nullable<decimal> mi377 { get; set; }
    }
}
