//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Form47
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string si68 { get; set; }
        public string si421 { get; set; }
        public string si15 { get; set; }
        public string si16 { get; set; }
        public string si383 { get; set; }
        public string si188 { get; set; }
        public string si2 { get; set; }
        public string di384 { get; set; }
        public Nullable<decimal> mi385 { get; set; }
        public Nullable<decimal> mi386 { get; set; }
        public Nullable<decimal> mi387 { get; set; }
    }
}
