//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Form28
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string si2295 { get; set; }
        public string si234 { get; set; }
        public string si2 { get; set; }
        public string di9 { get; set; }
        public string di10 { get; set; }
        public Nullable<decimal> pi12 { get; set; }
        public Nullable<decimal> mi235 { get; set; }
        public Nullable<decimal> mi236 { get; set; }
        public Nullable<decimal> mi237 { get; set; }
        public Nullable<decimal> mi238 { get; set; }
        public Nullable<decimal> mi366 { get; set; }
    }
}
