//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Form06
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string si68 { get; set; }
        public string si421 { get; set; }
        public string si15 { get; set; }
        public string si16 { get; set; }
        public string si69 { get; set; }
        public string si34 { get; set; }
        public string si35 { get; set; }
        public string si36 { get; set; }
        public string si1 { get; set; }
        public string si2 { get; set; }
        public string di9 { get; set; }
        public string di10 { get; set; }
        public string si11 { get; set; }
        public string si37 { get; set; }
        public string si71 { get; set; }
        public string si19 { get; set; }
        public string di72 { get; set; }
        public string si58 { get; set; }
        public Nullable<decimal> mi38 { get; set; }
        public Nullable<decimal> mi39 { get; set; }
        public string si27 { get; set; }
        public string si28 { get; set; }
        public string si80 { get; set; }
        public string si29 { get; set; }
        public string di30 { get; set; }
        public Nullable<decimal> mi31 { get; set; }
        public Nullable<decimal> mi60 { get; set; }
        public Nullable<decimal> pi59 { get; set; }
        public Nullable<decimal> mi40 { get; set; }
        public Nullable<decimal> mi41 { get; set; }
    }
}
