//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Form48
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string si388 { get; set; }
        public string si423 { get; set; }
        public string si2462 { get; set; }
        public string si2463 { get; set; }
        public Nullable<decimal> pi2464 { get; set; }
        public Nullable<decimal> mi389 { get; set; }
        public string si68 { get; set; }
        public string si424 { get; set; }
        public string si421 { get; set; }
        public string si15 { get; set; }
        public string si16 { get; set; }
        public string si390 { get; set; }
        public Nullable<int> ii391 { get; set; }
        public string si2 { get; set; }
        public string di9 { get; set; }
        public string di10 { get; set; }
        public string si392 { get; set; }
        public string si393 { get; set; }
        public string si427 { get; set; }
        public Nullable<decimal> pi251 { get; set; }
        public Nullable<decimal> pi12 { get; set; }
        public string si395 { get; set; }
        public Nullable<decimal> mi396 { get; set; }
        public string si58 { get; set; }
        public Nullable<decimal> mi397 { get; set; }
    }
}
