//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Form29
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string si68 { get; set; }
        public string si422 { get; set; }
        public string si15 { get; set; }
        public string si16 { get; set; }
        public string si69 { get; set; }
        public string si239 { get; set; }
        public string si188 { get; set; }
        public string si240 { get; set; }
        public string si241 { get; set; }
        public string si2 { get; set; }
        public string di9 { get; set; }
        public string di10 { get; set; }
        public string si242 { get; set; }
        public Nullable<decimal> pi12 { get; set; }
        public Nullable<decimal> mi243 { get; set; }
        public Nullable<decimal> mi244 { get; set; }
        public Nullable<decimal> mi245 { get; set; }
        public Nullable<decimal> mi246 { get; set; }
        public Nullable<decimal> mi247 { get; set; }
    }
}
