//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xbrl_Form50
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string Jenis_Piutang_Pembiayaan { get; set; }
        public string Golongan_Nasabah__Debitur_ { get; set; }
        public string Kategori_usaha_nasabah { get; set; }
        public string Jenis_Penggunaan { get; set; }
        public string Lokasi_Proyek { get; set; }
        public string Sektor_Ekonomi { get; set; }
        public Nullable<decimal> Jumlah___Rupiah { get; set; }
        public Nullable<decimal> Jumlah___Valas { get; set; }
        public Nullable<decimal> Jumlah___Total { get; set; }
    }
}
