//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xbrl_FormLA06
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string Nomor_Nasabah { get; set; }
        public string Golongan_Nasabah__Tertagih_ { get; set; }
        public string Klasifikasi_Nasabah_Hubungan_dengan_bank { get; set; }
        public string Klasifikasi_Nasabah_Status { get; set; }
        public string Negara_Pihak_Lawan { get; set; }
        public string Jenis_Instrumen { get; set; }
        public string Jenis_Valuta { get; set; }
        public string Jangka_Waktu_Mulai { get; set; }
        public string Jangka_Waktu_Jatuh_Tempo { get; set; }
        public string Kategori_Portfolio { get; set; }
        public string Peringkat_Lembaga_Pemeringkat { get; set; }
        public string Peringkat_Nilai_Peringkat { get; set; }
        public string Peringkat_Tanggal_Pemeringkatan { get; set; }
        public string Nominal { get; set; }
        public string Persentase_Imbalan { get; set; }
        public string Jumlah_Bulan_Lalu { get; set; }
        public string Jumlah_Debet { get; set; }
        public string Jumlah_Kredit { get; set; }
        public string Jumlah_Lainnya { get; set; }
        public string Jumlah_Bulan_Laporan { get; set; }
        public string Imbalan_yang_akan_diterima { get; set; }
        public string Kualitas { get; set; }
        public string Agunan___Jaminan_Jenis_Agunan__Jaminan { get; set; }
        public string Agunan___Jaminan_Nomor_Agunan__jaminan { get; set; }
        public string Agunan___Jaminan_Sifat { get; set; }
        public string Agunan___Jaminan_Golongan_Penerbit { get; set; }
        public string Agunan___Jaminan_Tanggal_Penilaian_Terakhir { get; set; }
        public string Agunan___Jaminan_Jumlah { get; set; }
        public string Agunan___Jaminan_Agunan__jaminan_Yang_Dapat_Diperhitungkan { get; set; }
        public string Agunan___Jaminan_Bagian_Dijamin { get; set; }
        public string Cadangan_Kerugian_Penurunan_Nilai_Individual { get; set; }
        public string Kolektif { get; set; }
    }
}
