//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xbrl_SysCounter
    {
        public string scId { get; set; }
        public string scType { get; set; }
        public int scPrefix { get; set; }
        public string scName { get; set; }
        public string scCurrent { get; set; }
    }
}
