//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xbrl_Form23
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string Uraian { get; set; }
        public string Jenis_Valuta { get; set; }
        public string Jangka_Waktu { get; set; }
        public Nullable<decimal> Jumlah { get; set; }
        public string Kualitas { get; set; }
        public Nullable<decimal> Cadangan_Kerugian_Penurunan_Nilai { get; set; }
    }
}
