//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xbrl_Form51
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string Uraian { get; set; }
        public Nullable<decimal> Jumlah___Rupiah { get; set; }
        public Nullable<decimal> Jumlah___Valas { get; set; }
        public Nullable<decimal> Jumlah___Jumlah { get; set; }
    }
}
