//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xbrl_Generated
    {
        public int PK_xbrl_Generated_ID { get; set; }
        public string TaxoName { get; set; }
        public string BankCode { get; set; }
        public string FileLink { get; set; }
        public string FileName { get; set; }
        public Nullable<bool> IsAlreadyValidate { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public Nullable<System.DateTime> ReportingDate { get; set; }
        public Nullable<int> CheckerMakerApproval { get; set; }
        public Nullable<System.DateTime> StartGeneratedDate { get; set; }
        public Nullable<System.DateTime> EndGeneratedDate { get; set; }
        public Nullable<int> RowsCount { get; set; }
        public Nullable<System.DateTime> StartValidateDate { get; set; }
        public Nullable<System.DateTime> EndValidateDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
    }
}
