//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xbrl_Form17
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string Jenis_aset { get; set; }
        public string Nomor_Aset { get; set; }
        public string Waktu_Perolehan { get; set; }
        public string Metode_Pengukuran { get; set; }
        public string Jenis_Valuta { get; set; }
        public string Jangka_Waktu___Mulai { get; set; }
        public string Jangka_Waktu___Jatuh_Tempo { get; set; }
        public Nullable<decimal> Jumlah { get; set; }
        public Nullable<decimal> Akumulasi_Amortisasi { get; set; }
        public Nullable<decimal> Cadangan_Kerugian_Penurunan_Nilai { get; set; }
    }
}
