//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xbrl_FormAnak12
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string Nomor_Nasabah { get; set; }
        public string Golongan_Nasabah__Emiten_ { get; set; }
        public string Status_Nasabah { get; set; }
        public string Negara_Pihak_Lawan { get; set; }
        public string Jenis_Valuta { get; set; }
        public string Waktu_Penyertaan { get; set; }
        public string Metode_Penyertaan { get; set; }
        public string Tujuan_Penyertaan { get; set; }
        public Nullable<decimal> Bagian_Penyertaan { get; set; }
        public Nullable<decimal> Nominal_Penyertaan { get; set; }
        public Nullable<decimal> Jumlah___Bulan_Lalu { get; set; }
        public Nullable<decimal> Jumlah___Debet { get; set; }
        public Nullable<decimal> Jumlah___Kredit { get; set; }
        public Nullable<decimal> Jumlah___Lainnya { get; set; }
        public Nullable<decimal> Jumlah___Bulan_Laporan { get; set; }
        public string Kualitas { get; set; }
        public Nullable<decimal> Agunan_Jaminan_yang_Dapat_Diperhitungkan { get; set; }
        public Nullable<decimal> Cadangan_Kerugian___Individual { get; set; }
        public Nullable<decimal> Cadangan_Kerugian___Kolektif { get; set; }
    }
}
