//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xbrl_Form08
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string Nomor_Rekening { get; set; }
        public string Jenis { get; set; }
        public string Jenis_Akad { get; set; }
        public string Jangka_Waktu___Mulai { get; set; }
        public string Jangka_Waktu___Jatuh_Tempo { get; set; }
        public Nullable<decimal> Persentase_Imbalan { get; set; }
        public Nullable<decimal> Nominal { get; set; }
        public string Sumber_Dana { get; set; }
        public Nullable<decimal> Jumlah___Bulan_Lalu { get; set; }
        public Nullable<decimal> Jumlah___Bulan_Laporan { get; set; }
        public Nullable<decimal> Imbalan_yang_akan_diterima { get; set; }
    }
}
