//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xbrl_FormAnak06
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string Nomor_Nasabah { get; set; }
        public string Golongan_Nasabah { get; set; }
        public string Klasifikasi_Nasabah___Hubungan_dengan_bank { get; set; }
        public string Klasifikasi_Nasabah___Status { get; set; }
        public string Negara_Pihak_Lawan { get; set; }
        public string Jenis_Instrumen { get; set; }
        public string Jenis_valuta { get; set; }
        public string Jangka_Waktu___Mulai { get; set; }
        public string Jangka_Waktu___Jatuh_Tempo { get; set; }
        public string Kategori_Portofolio { get; set; }
        public string Peringkat___Lembaga_Pemeringkat { get; set; }
        public string Peringkat___Nilai_Pemeringkat { get; set; }
        public string Peringkat___Tanggal_Pemeringkatan { get; set; }
        public Nullable<decimal> Nominal { get; set; }
        public Nullable<decimal> Persentase_Imbalan { get; set; }
        public Nullable<decimal> Jumlah___Bulan_Lalu { get; set; }
        public Nullable<decimal> Jumlah___Debet { get; set; }
        public Nullable<decimal> Jumlah___Kredit { get; set; }
        public Nullable<decimal> Jumlah___Lainnya { get; set; }
        public Nullable<decimal> Jumlah___Bulan_Laporan { get; set; }
        public string Kualitas { get; set; }
        public string Agunan___Jaminan___Jenis_Agunan_Jaminan { get; set; }
        public string Agunan___Jaminan___Nomor_Agunan_Jaminan { get; set; }
        public string Agunan___Jaminan___Sifat { get; set; }
        public string Agunan___Jaminan___Golongan_Penerbit { get; set; }
        public string Agunan___Jaminan___Tanggal_Penilaian_Terakhir { get; set; }
        public Nullable<decimal> Agunan___Jaminan___Jumlah { get; set; }
        public Nullable<decimal> Agunan__Jaminan___Agunan__Jaminan_yang_Dapat_Diperhitungkan { get; set; }
        public Nullable<decimal> Agunan___Jaminan___Bagian_Dijamin { get; set; }
        public Nullable<decimal> Cadangan_Kerugian_Penurunan_Nilai___Individual { get; set; }
        public Nullable<decimal> Cadangan_Kerugian_Penurunan_Nilai___Kolektif { get; set; }
    }
}
