//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class XbrlOnProgressValidationThread
    {
        public long PK_XbrlOnProgressValidationThread_Id { get; set; }
        public Nullable<long> FK_XbrlInstanceManagement_Id { get; set; }
        public string TaxoDate { get; set; }
        public string InstanceName { get; set; }
    }
}
