//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xbrl_FormGabungan01
    {
        public string ID { get; set; }
        public string Periode { get; set; }
        public string BIBankId { get; set; }
        public string Parent { get; set; }
        public string Child { get; set; }
        public string Prefix { get; set; }
        public string Description { get; set; }
        public Nullable<int> Sandi { get; set; }
        public string Path { get; set; }
        public decimal Amount { get; set; }
    }
}
