//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class XbrlInstanceManagement
    {
        public long PK_XbrlInstanceManagement_Id { get; set; }
        public string TaxoDate { get; set; }
        public string FormName { get; set; }
        public string InstanceName { get; set; }
        public string BankCode { get; set; }
        public Nullable<System.DateTime> StartProcessDate { get; set; }
        public Nullable<System.DateTime> EndProcessDate { get; set; }
        public Nullable<long> InstanceSize { get; set; }
        public Nullable<long> MemoryReserved { get; set; }
        public Nullable<byte> ProcessStatus { get; set; }
        public string ProcessDesc { get; set; }
        public Nullable<byte> ProcessMethod { get; set; }
    }
}
