//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xbrl_FormLA04
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string Nomor_Nasabah { get; set; }
        public string Golongan_Nasabah__pihak_lawan_ { get; set; }
        public string Klasifikasi_Nasabah_Hubungan_dengan_bank { get; set; }
        public string Klasifikasi_Nasabah_Status { get; set; }
        public string Negara_Pihak_Lawan { get; set; }
        public string Jenis { get; set; }
        public string Kontrak { get; set; }
        public string Variabel_yang_mendasari { get; set; }
        public string Nomor_referensi_transaksi__deal_number_ { get; set; }
        public string Jenis_Valuta { get; set; }
        public string Jangka_Waktu_Mulai { get; set; }
        public string Jangka_Waktu_Jatuh_tempo { get; set; }
        public string Sumber_Dana { get; set; }
        public string Kategori_portofolio { get; set; }
        public string Peringkat_Lembaga_Pemeringkat { get; set; }
        public string Peringkat_Nilai_Peringkat { get; set; }
        public string Peringkat_Tanggal_Pemeringkatan { get; set; }
        public string Kualitas { get; set; }
        public string Jumlah_Bulan_Lalu { get; set; }
        public string Jumlah_Bulan_Laporan { get; set; }
        public string Agunan_Jaminan_Jenis { get; set; }
        public string Agunan_Jaminan_Nomor_Agunan__jaminan { get; set; }
        public string Agunan_Jaminan_Sifat { get; set; }
        public string Agunan_Jaminan_Golongan_Penerbit { get; set; }
        public string Agunan_Jaminan_Tanggal_Penilaian_Terakhir { get; set; }
        public string Agunan_Jaminan_Jumlah { get; set; }
        public string Agunan_Jaminan_Agunan__jaminan_Yang_Dapat_Diperhitungkan { get; set; }
        public string Agunan_Jaminan_Bagian_Dijamin { get; set; }
        public string Cadangan_Kerugian_Penurunan_Nilai_CKPN_Individual { get; set; }
        public string Cadangan_Kerugian_Penurunan_Nilai_CKPN_Kolektif { get; set; }
    }
}
