//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xbrl_FormLA05
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string Nomor_Nasabah { get; set; }
        public string Golongan_Nasabah__Penerbit__Tertarik_ { get; set; }
        public string Klasifikasi_Nasabah_Hubungan_dengan_bank { get; set; }
        public string Klasifikasi_Nasabah_Status { get; set; }
        public string Negara_Pihak_Lawan { get; set; }
        public string Jenis_Instrumen { get; set; }
        public string Fitur_Tambahan { get; set; }
        public string Status_Instrumen { get; set; }
        public string Jenis_Valuta { get; set; }
        public string Jangka_waktu_Mulai { get; set; }
        public string Jangka_waktu_Jatuh_Tempo { get; set; }
        public string Sumber_Dana { get; set; }
        public string Metode_Pengukuran { get; set; }
        public string Kategori_Portfolio { get; set; }
        public string Peringkat_Lembaga_Pemeringkat { get; set; }
        public string Peringkat_Nilai_Peringkat { get; set; }
        public string Peringkat_Tanggal_Pemeringkat { get; set; }
        public string Jenis_Akad { get; set; }
        public string Karakteristik_akad_Metode_Bagi_Hasil { get; set; }
        public string Karakteristik_akad_Persentase_nisbah { get; set; }
        public string Harga_Perolehan { get; set; }
        public string Nominal { get; set; }
        public string Periode_Pembayaran_Imbalan { get; set; }
        public string Persentase_Imbalan_Awal_Kontrak { get; set; }
        public string Persentase_Imbalan_Bulan_Laporan { get; set; }
        public string Jumlah_Bulan_Lalu { get; set; }
        public string Jumlah_Debet { get; set; }
        public string Jumlah_Kredit { get; set; }
        public string Jumlah_Lainnya { get; set; }
        public string Jumlah_Bulan_Laporan { get; set; }
        public string Premium____Discount___Marked_to_Market__MtM_ { get; set; }
        public string Imbalan_yang_akan_diterima { get; set; }
        public string Kualitas { get; set; }
        public string Agunan_Jaminan_Jenis_Agunan__Jaminan { get; set; }
        public string Agunan_Jaminan_Nomor_Agunan__jaminan { get; set; }
        public string Agunan_Jaminan_Sifat { get; set; }
        public string Agunan_Jaminan_Golongan_Penerbit { get; set; }
        public string Agunan_Jaminan_Tanggal_Penilaian_Terakhir { get; set; }
        public string Agunan_Jaminan_Jumlah_____Agunan_Jaminan_Agunan__jaminan_Dapat_Diperhitungkan { get; set; }
        public string Agunan_Jaminan_Bagian_Dijamin { get; set; }
        public string CKPN_Individual_Umum { get; set; }
        public string CKPN_Kolektif_Khusus { get; set; }
    }
}
