//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xbrl_FormLA12
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string Nomor_Nasabah { get; set; }
        public string Golongan_Nasabah__emiten_ { get; set; }
        public string Status_Nasabah { get; set; }
        public string Negara_Pihak_Lawan { get; set; }
        public string Jenis_Valuta { get; set; }
        public string Waktu_Penyertaan { get; set; }
        public string Metode_Penyertaan { get; set; }
        public string Tujuan_Penyertaan { get; set; }
        public string Bagian_Penyertaan { get; set; }
        public string Nominal { get; set; }
        public string Jumlah_Bulan_Lalu { get; set; }
        public string Jumlah_Debet { get; set; }
        public string Jumlah_Kredit { get; set; }
        public string Jumlah_Lainnya { get; set; }
        public string Jumlah_Bulan_Laporan { get; set; }
        public string Kualitas { get; set; }
        public string Agunan__Jaminan_yang_dapat_diperhitungkan { get; set; }
        public string Cadangan_Kerugian_Individual { get; set; }
        public string Cadangan_Kerugian_Kolektif { get; set; }
    }
}
