//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xbrl_FormLA11
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string Nomor_Nasabah { get; set; }
        public string Golongan_Nasabah { get; set; }
        public string Klasifikasi_Nasabah_Hubungan_Dengan_Bank { get; set; }
        public string Klasifikasi_Nasabah_Status { get; set; }
        public string Klasifikasi_Nasabah_Kategori_Usaha { get; set; }
        public string Nomor_Rekening { get; set; }
        public string Jenis_Valuta { get; set; }
        public string Jangka_waktu_Mulai { get; set; }
        public string Jangka_waktu_Jatuh_Tempo_Kontraktual____Sumber_Dana { get; set; }
        public string Lokasi_Proyek { get; set; }
        public string Jenis_Pembiayaan { get; set; }
        public string Sifat_Pembiayaan { get; set; }
        public string Jenis_Penggunaan { get; set; }
        public string Orientasi_Penggunaan { get; set; }
        public string Sektor_Ekonomi { get; set; }
        public string Kategori_Portofolio { get; set; }
        public string Peringkat__Lembaga_Pemeringkatan { get; set; }
        public string Peringkat__Nilai_Peringkat { get; set; }
        public string Peringkat__Tanggal_Pemeringkatan { get; set; }
        public string Jenis_Akad { get; set; }
        public string Karakteristik_Akad_Jenis_Aset { get; set; }
        public string Karakteristik_Akad_Perolehan_Aset_Waktu_Perolehan { get; set; }
        public string Karakteristik_Akad_Perolehan_Aset_Jenis_Valuta { get; set; }
        public string Karakteristik_Akad_Perolehan_Aset_Harga_Perolehan { get; set; }
        public string Karakteristik_Akad_Penyusutan__Amortisasi_Jumlah_Periode { get; set; }
        public string Karakteristik_Akad_Penyusutan__Amortisasi_Metode { get; set; }
        public string Periode_Pembayaran_Sewa { get; set; }
        public string Nilai_Kontrak { get; set; }
        public string Nilai_Sewa_Per_Periode { get; set; }
        public string Persentase_Imbalan { get; set; }
        public string Akumulasi_Penyusutan___Amortisasi { get; set; }
        public string Cadangan_Penurunan_Nilai_Aset_Ijarah { get; set; }
        public string Tunggakan_Hari { get; set; }
        public string Tunggakan_Pokok_Jumlah { get; set; }
        public string Tunggakan_Imbalan_Akumulasi { get; set; }
        public string Imbalan_yang_akan_diterima { get; set; }
        public string Kualitas { get; set; }
        public string Agunan_Jaminan_Jenis_Agunan__Jaminan { get; set; }
        public string Agunan_Jaminan_Nomor_Agunan__jaminan { get; set; }
        public string Agunan_Jaminan_Sifat { get; set; }
        public string Agunan_Jaminan_Golongan_Penerbit { get; set; }
        public string Agunan_Jaminan_Tanggal_Penilaian_Terakhir { get; set; }
        public string Agunan_Jaminan_Jumlah { get; set; }
        public string Agunan_Jaminan_Agunan__jaminan_Dapat_Diperhitungkan { get; set; }
        public string Agunan_Jaminan_Bagian_Dijamin { get; set; }
        public string CKPN_Individual { get; set; }
        public string CKPN_Kolektif { get; set; }
    }
}
