//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xbrl_Form20
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string Nomor_Aset { get; set; }
        public string Jenis_Aset { get; set; }
        public string Waktu_Perolehan { get; set; }
        public string Jenis_Valuta { get; set; }
        public string Sumber_Perolehan { get; set; }
        public string Metode_Pengukuran { get; set; }
        public string Status_Aset { get; set; }
        public Nullable<decimal> Jumlah { get; set; }
        public Nullable<decimal> Akumulasi_Penyusutan_Amortisasi { get; set; }
        public Nullable<decimal> CKPN_aset_tetap_dan_inventaris { get; set; }
        public string Lokasi_Aset { get; set; }
    }
}
