//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xbrl_Form2A
    {
        public string ID { get; set; }
        public string periode { get; set; }
        public string BIBankID { get; set; }
        public string parent { get; set; }
        public string child { get; set; }
        public string Prefix { get; set; }
        public string Description { get; set; }
        public Nullable<int> Sandi { get; set; }
        public string path { get; set; }
        public decimal Amount { get; set; }
    }
}
