//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xbrl_FormLA08
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string Nomor_Nasabah { get; set; }
        public string Golongan_Nasabah { get; set; }
        public string Klasifikasi_Nasabah_Hubungan_Dengan_Bank { get; set; }
        public string Klasifikasi_Nasabah_Status { get; set; }
        public string Klasifikasi_Nasabah_Kategori_Usaha { get; set; }
        public string Nomor_Rekening { get; set; }
        public string Jenis_Valuta { get; set; }
        public string Jangka_waktu_Mulai { get; set; }
        public string Jangka_waktu_Jatuh_Tempo_Kontraktual { get; set; }
        public string Sumber_Dana { get; set; }
        public string Lokasi { get; set; }
        public string Jenis_Piutang { get; set; }
        public string Sifat_Piutang { get; set; }
        public string Jenis_Penggunaan { get; set; }
        public string Orientasi_Penggunaan { get; set; }
        public string Sektor_Ekonomi { get; set; }
        public string Kategori_Portofolio { get; set; }
        public string Peringkat_Lembaga_Pemeringkatan { get; set; }
        public string Peringkat__Nilai_Peringkat { get; set; }
        public string Peringkat__Tanggal_Pemeringkatan { get; set; }
        public string Nilai_Kontrak { get; set; }
        public string Persentase_Imbalan_Awal_Kontrak { get; set; }
        public string Persentase_Imbalan_Bulan_Laporan { get; set; }
        public string Saldo_Harga_Pokok { get; set; }
        public string Saldo_Margin_Ditangguhkan { get; set; }
        public string Jumlah_Bulan_Lalu { get; set; }
        public string Jumlah_Bulan_Laporan { get; set; }
        public string Tunggakan_Hari { get; set; }
        public string Tunggakan_Pokok { get; set; }
        public string Tunggakan_Margin { get; set; }
        public string Imbalan_Yg_Akan_Diterima { get; set; }
        public string Kualitas { get; set; }
        public string Agunan_Jaminan_Jenis_Agunan__Jaminan { get; set; }
        public string Agunan_Jaminan_Nomor_Agunan__jaminan { get; set; }
        public string Agunan_Jaminan_Sifat { get; set; }
        public string Agunan_Jaminan_Golongan_Penerbit { get; set; }
        public string Agunan_Jaminan_Tanggal_Penilaian_Terakhir { get; set; }
        public string Agunan_Jaminan_Jumlah { get; set; }
        public string Agunan_Jaminan_Agunan_jaminan_Dapat_Diperhitungkan { get; set; }
        public string Agunan_Jaminan_Bagian_Dijamin { get; set; }
        public string CKPN_Individual { get; set; }
        public string CKPN_Kolektif { get; set; }
    }
}
