//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xbrl_Form42
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string Golongan_Nasabah__Pemegang_Saham_ { get; set; }
        public string Klasifikasi_Pemegang_Saham___Hubungan_dengan_Bank { get; set; }
        public string Klasifikasi_Pemegang_Saham___Status { get; set; }
        public string Negara_Pihak_Lawan { get; set; }
        public string Jenis_Instrumen { get; set; }
        public Nullable<decimal> Nominal { get; set; }
        public Nullable<decimal> Jumlah { get; set; }
    }
}
