//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xbrl_Form07
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string Nomor_Nasabah { get; set; }
        public string Golongan_Nasabah__Penerbit_Tertarik_ { get; set; }
        public string Klasifikasi___Hubungan_dengan_bank { get; set; }
        public string Klasifikasi___Status { get; set; }
        public string Negara_Pihak_Lawan { get; set; }
        public string Jenis_Instrumen { get; set; }
        public string Fitur_Tambahan { get; set; }
        public string Status_Instrumen { get; set; }
        public string Jenis_Valuta { get; set; }
        public string Jangka_waktu___Mulai { get; set; }
        public string Jangka_waktu___Jatuh_Tempo { get; set; }
        public string Sumber_Dana { get; set; }
        public string Metode_Pengukuran { get; set; }
        public string Kategori_Portofolio { get; set; }
        public string Peringkat___Lembaga_Pemeringkat { get; set; }
        public string Peringkat___Nilai_Peringkat { get; set; }
        public string Peringkat___Tanggal_Pemeringkatan { get; set; }
        public string Jenis_Akad { get; set; }
        public string Karakteristik_akad___Metode_Bagi_Hasil { get; set; }
        public decimal Harga_Perolehan { get; set; }
        public Nullable<decimal> Karakteristik_Akad___Persentase_nisbah { get; set; }
        public Nullable<decimal> Nominal { get; set; }
        public string Periode_Pembayaran_Imbalan { get; set; }
        public Nullable<decimal> Persentase_Imbalan___Awal_Kontrak { get; set; }
        public Nullable<decimal> Persentase_Imbalan___Bulan_Laporan { get; set; }
        public Nullable<decimal> Jumlah___Bulan_Lalu { get; set; }
        public Nullable<decimal> Jumlah___Debet { get; set; }
        public Nullable<decimal> Jumlah___Kredit { get; set; }
        public Nullable<decimal> Jumlah___Lainnya { get; set; }
        public Nullable<decimal> Jumlah___Bulan_Laporan { get; set; }
        public decimal Premium____Discount___Marked_to_Market__MtM_ { get; set; }
        public Nullable<decimal> Imbalan_yang_akan_diterima { get; set; }
        public string Kualitas { get; set; }
        public string Agunan___Jenis_Agunan { get; set; }
        public string Agunan___Nomor_Agunan { get; set; }
        public string Agunan___Sifat { get; set; }
        public string Agunan___Golongan_Penerbit { get; set; }
        public string Agunan___Tanggal_Penilaian_Terakhir { get; set; }
        public Nullable<decimal> Agunan___Jumlah { get; set; }
        public Nullable<decimal> Agunan___Yang_dapat_diperhitungkan { get; set; }
        public Nullable<decimal> Agunan___Jaminan___Bagian_Dijamin { get; set; }
        public Nullable<decimal> CKPN___Individual { get; set; }
        public Nullable<decimal> CKPN___Kolektif { get; set; }
    }
}
