//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xbrl_Form36
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string Nomor_Nasabah { get; set; }
        public string Golongan_Nasabah__Kreditur_ { get; set; }
        public string Klasifikasi_Nasabah__Bank____Hubungan_dengan_Bank_Lain { get; set; }
        public string Klasifikasi_Nasabah__Bank____Status { get; set; }
        public string Negara_Pihak_Lawan { get; set; }
        public string Jenis_Instrumen { get; set; }
        public string Nomor_Rekening { get; set; }
        public string Fitur_Tambahan { get; set; }
        public string Jenis_Valuta { get; set; }
        public string Jangka_Waktu___Mulai { get; set; }
        public string Jangka_Waktu___Jatuh_Tempo { get; set; }
        public string Jenis_Akad { get; set; }
        public string Karakteristik_Akad___Sifat_Investasi { get; set; }
        public string Karakteristik_Akad___Metode_Bagi_Hasil { get; set; }
        public Nullable<decimal> Karakteristik_Akad___Persentase_Nisbah { get; set; }
        public Nullable<decimal> Nominal { get; set; }
        public Nullable<decimal> Persentase_Imbalan___Awal_Kontrak { get; set; }
        public Nullable<decimal> Persentase_Imbalan___Bulan_Laporan { get; set; }
        public Nullable<decimal> Jumlah___Bulan_Lalu { get; set; }
        public Nullable<decimal> Jumlah___Debet { get; set; }
        public Nullable<decimal> Jumlah___Kredit { get; set; }
        public Nullable<decimal> Jumlah___Lainnya { get; set; }
        public Nullable<decimal> Jumlah___Bulan_Laporan { get; set; }
        public Nullable<decimal> Kelonggaran_Tarik___Committed { get; set; }
        public Nullable<decimal> Kelonggaran_Tarik___Uncommitted_ { get; set; }
    }
}
