//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xbrl_Base
    {
        public int ID { get; set; }
        public string elementID { get; set; }
        public string elementType { get; set; }
        public string elementName { get; set; }
        public string elementData { get; set; }
        public string elementCode { get; set; }
        public string elementDef { get; set; }
    }
}
