//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xbrl_Form19
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string Nomor_Nasabah { get; set; }
        public string Golongan_Nasabah__Produsen_ { get; set; }
        public string Klasifikasi_Nasabah___Hubungan_dengan_Bank { get; set; }
        public string Klasifikasi_Nasabah___Status { get; set; }
        public string Jenis_Aset { get; set; }
        public string Nomor_Rekening { get; set; }
        public string Jenis_Valuta { get; set; }
        public string Jangka_Waktu___Mulai { get; set; }
        public string Jangka_Waktu___Jatuh_Tempo { get; set; }
        public string Tujuan { get; set; }
        public string Metode_Pengakuan_Pendapatan { get; set; }
        public Nullable<decimal> Harga_Beli_kepada_Produsen { get; set; }
        public Nullable<decimal> Persentase_Penyelesaian { get; set; }
        public Nullable<decimal> Termin_Istishna { get; set; }
        public Nullable<decimal> Jumlah { get; set; }
    }
}
