//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xbrl_Form14
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string Agunan___Jaminan___Jenis_Agunan___Jaminan { get; set; }
        public string Agunan___Jaminan___Nomor_Agunan_Jaminan { get; set; }
        public string Agunan___Jaminan___Sifat { get; set; }
        public string Agunan___Jaminan___Golongan_Penerbit { get; set; }
        public string Agunan___Jaminan___Tanggal_Penilaian_Terakhir { get; set; }
        public Nullable<decimal> Agunan___Jaminan___Jumlah { get; set; }
        public Nullable<decimal> Agunan___Jaminan___Agunan_yang_Diperhitungkan { get; set; }
        public Nullable<decimal> Agunan___Jaminan___Bagian_Dijamin { get; set; }
        public string Nomor_Nasabah { get; set; }
        public string Golongan_Nasabah { get; set; }
        public string Klasifikasi_Nasabah___Hubungan_dengan_bank { get; set; }
        public string Klasifikasi_Nasabah___Status { get; set; }
        public string Klasifikasi_Nasabah___Kategori_Usaha { get; set; }
        public string Nomor_Rekening { get; set; }
        public string Jenis_Valuta { get; set; }
        public string Jangka_waktu___Mulai { get; set; }
        public string Jangka_waktu___Jatuh_tempo { get; set; }
        public string Sumber_Dana { get; set; }
        public string Lokasi_Proyek { get; set; }
        public string Jenis_Pembiayaan { get; set; }
        public string Sifat_Pembiayaan { get; set; }
        public string Jenis_Penggunaan { get; set; }
        public string Orientasi_Penggunaan { get; set; }
        public string Sektor_Ekonomi { get; set; }
        public string Kategori_Portofolio { get; set; }
        public string Peringkat___Lembaga_Pemeringkatan { get; set; }
        public string Peringkat___Nilai_Peringkat { get; set; }
        public string Peringkat___Tanggal_Pemeringkatan { get; set; }
        public string Jenis_Akad { get; set; }
        public string Kategori_Akad___Perolehan_Aset___Waktu_Perolehan { get; set; }
        public string Kategori_Akad___Perolehan_Aset___Jenis_Valuta { get; set; }
        public Nullable<decimal> Kategori_Akad___Perolehan_Aset___Harga_Perolehan { get; set; }
        public string Kategori_Akad___Penyusutan___Jumlah_Periode { get; set; }
        public string Kategori_Akad___Penyusutan___Metode { get; set; }
        public string Periode_Pembiayaan_Sewa { get; set; }
        public Nullable<decimal> Nilai_Kontrak { get; set; }
        public Nullable<decimal> Persentase_imbalan { get; set; }
        public Nullable<decimal> Akumulasi_Penyusutan___Amortisasi { get; set; }
        public Nullable<decimal> Cadangan_Penurunan_Nilai_Aset_Ijarah { get; set; }
        public Nullable<decimal> Tunggakan_hari { get; set; }
        public Nullable<decimal> Tunggakan_pokok { get; set; }
        public Nullable<decimal> Tunggakan_imbalan { get; set; }
        public Nullable<decimal> Imbalan_yang_akan_diterima { get; set; }
        public string Kualitas { get; set; }
        public Nullable<decimal> CKPN___Individual { get; set; }
        public Nullable<decimal> CKPN___Kolektif { get; set; }
    }
}
