//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xbrl_Form05
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string Sandi { get; set; }
        public string Klasifikasi_Nasabah__Bank____Hubungan_dengan_Bank { get; set; }
        public string Klasifikasi_Nasabah__Bank____Status { get; set; }
        public string Klasifikasi_Nasabah__Bank____Jenis_Operasional { get; set; }
        public string Negara_Pihak_Lawan { get; set; }
        public string Jenis_Instrumen { get; set; }
        public string Jenis_Valuta { get; set; }
        public string Jangka_Waktu___Mulai { get; set; }
        public string Jangka_Waktu___Jatuh_Tempo { get; set; }
        public string Sumber_Dana { get; set; }
        public string Peringkat___Lembaga_Pemeringkat { get; set; }
        public string Peringkat___Nilai_Peringkat { get; set; }
        public string Peringkat___Tanggal_Pemeringkatan { get; set; }
        public string Jenis_Akad { get; set; }
        public string Karakteristik_Akad___Metode_Bagi_Hasil { get; set; }
        public Nullable<decimal> Karakteristik_Akad___Persentase_Nisbah { get; set; }
        public Nullable<decimal> Persentase_Imbalan___Awal_Kontrak { get; set; }
        public Nullable<decimal> Persentase_Imbalan___Bulan_Laporan { get; set; }
        public Nullable<decimal> Jumlah___Bulan_Lalu { get; set; }
        public Nullable<decimal> Jumlah___Debet { get; set; }
        public Nullable<decimal> Jumlah___Kredit { get; set; }
        public Nullable<decimal> Jumlah___Lainnya { get; set; }
        public Nullable<decimal> Jumlah___Bulan_Laporan { get; set; }
        public Nullable<decimal> Imbalan_yang_Akan_Diterima { get; set; }
        public string Kualitas { get; set; }
        public string Agunan___Jaminan___Jenis_Agunan_Jaminan { get; set; }
        public string Agunan___Jaminan___Nomor_Agunan_Jaminan { get; set; }
        public string Agunan___Jaminan___Sifat { get; set; }
        public string Agunan___Jaminan___Golongan_Penerbit { get; set; }
        public string Agunan___Jaminan___Tanggal_Penilaian_Terakhir { get; set; }
        public Nullable<decimal> Agunan___Jaminan___Jumlah { get; set; }
        public Nullable<decimal> Agunan___Jaminan___Agunan_Jaminan_yang_Dapat_Diperhitungkan { get; set; }
        public Nullable<decimal> Agunan___Jaminan___Bagian_Dijamin { get; set; }
        public Nullable<decimal> CKPN___Individual { get; set; }
        public Nullable<decimal> CKPN___Kolektif { get; set; }
    }
}
