//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xbrl_Form44
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string Nomor_Nasabah { get; set; }
        public string Golongan_Nasabah__Pihak_Lawan_ { get; set; }
        public string Klasifikasi_Nasabah___Hubungan_dengan_Bank { get; set; }
        public string Klasifikasi_Nasabah___Status { get; set; }
        public string Negara_Pihak_Lawan { get; set; }
        public string Jenis { get; set; }
        public string Status { get; set; }
        public string Kontrak { get; set; }
        public string Variabel_yang_Mendasari { get; set; }
        public string Tujuan { get; set; }
        public string Jenis_Hedging { get; set; }
        public string Nomor_Referensi_Transaksi { get; set; }
        public string Jenis_Valuta___Dasar { get; set; }
        public string Jenis_Valuta___Lawan { get; set; }
        public string Jangka_Waktu___Mulai { get; set; }
        public string Jangka_Waktu___Jatuh_Tempo { get; set; }
        public Nullable<decimal> Nominal { get; set; }
        public Nullable<decimal> Jumlah__Spot_Forward____Tagihan { get; set; }
        public Nullable<decimal> Jumlah__Spot_Forward____Kewajiban { get; set; }
    }
}
