//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xbrl_Form22
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string Nomor_Aset { get; set; }
        public string Jenis_Aset { get; set; }
        public string Waktu_Perolehan { get; set; }
        public Nullable<decimal> Harga_Pengambilalihan { get; set; }
        public string Jenis_Valuta { get; set; }
        public Nullable<decimal> Nilai_Bersih_yang_dapat_Direalisasikan { get; set; }
        public Nullable<decimal> Cadangan_Kerugian_Penurunan_Nilai { get; set; }
        public Nullable<decimal> Nilai_Tercatat { get; set; }
        public Nullable<decimal> Jumlah__AYDA_ { get; set; }
        public string Kualitas { get; set; }
        public string Lokasi_Aset { get; set; }
    }
}
