//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xbrl_Form47
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string Nomor_Nasabah { get; set; }
        public string Golongan_Nasabah { get; set; }
        public string Klasifikasi_Nasabah___Hubungan_dengan_Bank { get; set; }
        public string Klasifikasi_Nasabah___Status { get; set; }
        public string Jenis_Instrumen { get; set; }
        public string Nomor_Rekening { get; set; }
        public string Jenis_Valuta { get; set; }
        public string Tanggal_Hapus_Buku { get; set; }
        public Nullable<decimal> Jumlah { get; set; }
        public Nullable<decimal> Jumlah_Dipulihkan { get; set; }
        public Nullable<decimal> Baki_Debet { get; set; }
    }
}
