//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xbrl_ELEMENTbase
    {
        public int baseId { get; set; }
        public string ebName { get; set; }
        public string elementId { get; set; }
        public string elementName { get; set; }
        public string elementNillable { get; set; }
        public string elementType { get; set; }
        public string elementDataType { get; set; }
        public string elementDataValue { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    }
}
