//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xbrl_Form28
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string Golongan_Nasabah__Debitur_ { get; set; }
        public string Jenis_Instrumen { get; set; }
        public string Jenis_Valuta { get; set; }
        public string Jangka_Waktu___Mulai { get; set; }
        public string Jangka_Waktu___Jatuh_Tempo { get; set; }
        public Nullable<decimal> Persentase_Imbalan { get; set; }
        public Nullable<decimal> Jumlah___Bulan_Lalu { get; set; }
        public Nullable<decimal> Jumlah___Debet { get; set; }
        public Nullable<decimal> Jumlah___Kredit { get; set; }
        public Nullable<decimal> Jumlah___Lainnya { get; set; }
        public Nullable<decimal> Jumlah___Bulan_Laporan { get; set; }
    }
}
