//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xbrl_Form49
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string Jenis_Piutang_Pembiaayaan { get; set; }
        public string Jenis_Penggunaan { get; set; }
        public Nullable<decimal> Plafond_Piutang_Pembiayaan_Baru_yang_Disetujui_pada_Bulan_Laporan___Rupiah { get; set; }
        public Nullable<decimal> Plafond_Piutang_Pembiayaan_Baru_yang_Disetujui_pada_Bulan_Laporan___Valas { get; set; }
        public Nullable<decimal> Plafond_Piutang_Pembiayaan_Baru_yang_Disetujui_pada_Bulan_Laporan___Jumlah { get; set; }
        public Nullable<decimal> Realisasi_Piutang_Pembiayaan_Baru_pada_Bulan_Laporan___Rupiah { get; set; }
        public Nullable<decimal> Realisasi_Piutang_Pembiayaan_Baru_pada_Bulan_Laporan___Valas { get; set; }
        public Nullable<decimal> Realisasi_Piutang_Pembiayaan_Baru_pada_Bulan_Laporan___Jumlah { get; set; }
    }
}
