//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xbrl_BusinessValidation
    {
        public int ID { get; set; }
        public string Period { get; set; }
        public string BankCode { get; set; }
        public string instanceName { get; set; }
        public string nameVal { get; set; }
        public string satifiedVal { get; set; }
        public string unsatifiedVal { get; set; }
        public string describeVal { get; set; }
        public string ErrorRowId { get; set; }
    }
}
