//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBRLApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class xbrl_Form48
    {
        public int ID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Sandi_Bank { get; set; }
        public string Pemilik_Dana_Kreditur___Nomor_Nasabah { get; set; }
        public string Pemilik_Dana_Kreditur___Golongan_Nasabah { get; set; }
        public string Pemilik_Dana_Kreditur___Klasifikasi_Nasabah___Hubungan_dengan_Bank { get; set; }
        public string Pemilik_Dana_Kreditur___Klasifikasi_Nasabah___Status { get; set; }
        public Nullable<decimal> Pemilik_Dana_Kreditur___Persentase_Imbalan { get; set; }
        public Nullable<decimal> Pemilik_Dana_Kreditur___Jumlah { get; set; }
        public string Nasabah_Debitur___Nomor_Nasabah { get; set; }
        public string Nasabah_Debitur___Golongan_Penyalur { get; set; }
        public string Nasabah_Debitur___Golongan_Nasabah { get; set; }
        public string Nasabah_Debitur___Klasifikasi_Nasabah___Hubungan_dengan_Bank { get; set; }
        public string Nasabah_Debitur___Klasifikasi_Nasabah___Status { get; set; }
        public string Nasabah_Debitur___Klasifikasi_Nasabah___Jenis_Penyaluran { get; set; }
        public Nullable<int> Jumlah_Rekening { get; set; }
        public string Jenis_Valuta { get; set; }
        public string Jangka_Waktu___Mulai { get; set; }
        public string Jangka_Waktu___Jatuh_Tempo { get; set; }
        public string Lokasi_Proyek { get; set; }
        public string Jenis_Penggunaan { get; set; }
        public string Sektor_Ekonomi { get; set; }
        public Nullable<decimal> Persentase_Nisbah { get; set; }
        public string Tunggakan___Akumulasi { get; set; }
        public Nullable<decimal> Tunggakan___Jumlah { get; set; }
        public string Kualitas { get; set; }
        public Nullable<decimal> Jumlah { get; set; }
    }
}
